ALTER TABLE dbo.DOCUMENTS 
ADD 
    AGROUP_STATUS_CODE VARCHAR(1) NULL
        CONSTRAINT DF_DOCUMENTS_STATUS_AGROUP_CODE DEFAULT ('P')
        CONSTRAINT CK_DOCUMENTS_STATUS_AGROUP_CODE 
            CHECK (AGROUP_STATUS_CODE IN ('P', 'N', 'E', 'T', 'C')),

    AGROUP_DATE DATE NULL,
    AGROUP_HOUR TIME NULL,
    AGROUP_DATETIME DATETIME2 NULL,
    AGROUP_MESSAGE VARCHAR(250) NULL,
    AGROUP_LOG_ERROR_FILE VARCHAR(250) NULL;